### ISSUE TITLE
Error when running ol3 widget

### ISSUE THREAD

**Issue by osfrance** [Wirecloud/ol3-map-widget#1]
Hi, when I try to add OL3 widget, I had this error on the widget log : 

ReferenceError: Widget is not defined
Details
    File: js/main.js
    Line: 24

ReferenceError: ol is not defined
Details
    File: js/ol3-map-widget.js
    Line: 14

Thanks for help !

**Comment by aarranz** [comment]
We have updated the documentation 😃. Please, try again but using the new instructions.
