### ISSUE TITLE
Error occurs when clicking 'Layers' button

### ISSUE THREAD

**Issue by fisuda** [Wirecloud/ol3-map-widget#12]
Hello @aarranz  Sir,

The following error occurs when clicking 'Layers' button.
```
DashboardManagementAPI.js?v=33ed68a1f4ec0d53650ed4d41afb9985cd524a6c:171 Uncaught TypeError: invalid widget ref
    at Object.addWidget (DashboardManagementAPI.js?v=33ed68a1f4ec0d53650ed4d41afb9985cd524a6c:171)
    at HTMLDivElement.<anonymous> (ol3-map-widget.js:231)
```

File: js/ol3-map-widget.js:231

```
this.layers_widget = MashupPlatform.mashup.addWidget('CoNWeT/layer-selector/0.4', {refposition:event.target.getBoundingClientRect()});
```

It seems that this error occurs because of not found a widget 'CoNWeT/layer-selector/0.4'.
Although I looked for this source code, I wasn't able to find it.

If this widget is an open source, would you please tell me where it is?

**Comment by aarranz** [comment]
Hi @fisuda,

Sorry, it is true that the layer selector widget is currently not publicly available on github, I'm uploading it.

**Comment by fisuda** [comment]
Thank you for your reply. I understood. I expect it will be uploaded.

**Comment by aarranz** [comment]
Hi again,

you can find the code at: https://github.com/conwetlab/layer-selector-widget

This widget is very outdated and its code is too much complex, more taking into account what it does, so for now it is only useful for having some initial code.

In any case, our idea is to be able to configure the widget to be used for switching layers and to be able to disable this button if switching layers is not required. I will try to work on this regard on the following days.

**Comment by fisuda** [comment]
Hi @aarranz ,

I appreciate your kind response. I will keep your advice in mind, and try this widget.

By the way, I introduced Wirecloud to Japanese audience. Please have a look.

- https://www.letsfiware.jp/opendata-api-kakogawa/
- https://mashup.lab.fisuda.jp/88c5050d-bc96-4ca5-b766-e510b214a208/kagogawa_demo#view=workspace&tab=fiware
